core/urls.py
from django.urls import path
from core import views

app_name = "core"

urlpatterns = [
    path("",views.index,name="index"),
    path("products/",views.product_list,name="product_list"),
    path("pd/<pid>/<str:slug>/",views.product_detail,name="product_detail"),
     path("get_variation_price/",views.get_variation_price,name="get_variation_price"),
    path("categories/",views.category_list,name="category_list"),

    path("search/",views.search,name="search"),
    
    #Cart
    path("add-to-cart/",views.add_cart_,name="add-to-cart"),
    # path("add_to_cart/",views.add_to_cart,name="add-to-cart"),
    path("remove_cart/",views.remove_cart,name="remove_cart"),
    path("delete_cart/<int:product_id>/<int:cart_item_id>/",views.delete_cart,name="delete_cart"),
    path("cart/",views.cart,name="cart"),
    path("increment_cart_item/",views.increment_cart_item,name="increment_cart_item"),
    path("remove_coupon/<int:coupon_id>",views.remove_coupon,name="remove_coupon"),

    # Whishlist
    path("add_to_wishlist/",views.add_to_wishlist,name="add-to-whishlist"),
    path("wishlist/",views.view_wishlist,name="wishlist"),
    path("wishlist/remove/<int:id>/",views.delete_wishlist_item,name="delete_wishlist_item"),

    
    
    # Apply coupon
    path("cart/apply_coupon/",views.apply_coupon,name="apply_coupon"),
    path("checkout/",views.checkout,name="checkout"),
    path("placeorder/",views.placeorder,name="placeorder"),
    path("order/payment/<str:orderno>/",views.payment,name="payment"),
    path("paymenthandler/",views.paymenthandler,name="paymenthandler"),
    # path("payment_success/",views.payment_success,name="payment_success"),
    path("checkout/success/<str:orderno>/",views.checkout_success,name="checkout_success"),


]

grocery_ecom/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("core.urls")),
    path("user/", include("userauths.urls")),
    path("user/", include("user.urls")),
    path("ckeditor/", include("ckeditor_uploader.urls")),
    path("superadmin/", include("superadmin.urls")),

    

]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

userauths/urls.py
from django.urls import path
from userauths import views

app_name = "userauths"

urlpatterns = [
    path("login/",views.user_login, name="login"),
    path("sign-up/",views.register_view, name="sign-up"),
    path("verify_otp/",views.verify_otp, name='verify_otp'),
    path("send_otp/<str:email>/",views.send_otp, name='send_otp'),


    path("send_otp_for_reset/<str:email>/",views.send_otp_for_reset, name='send_otp_for_reset'),
    # path("accounts/password_change/",views.password_change, name="password_change"),
    # path("accounts/password_change/done/",views.forgot_password, name="password_change_done"),
    path("accounts/password_reset/",views.password_reset, name="password_reset"),
    path("verify_otp_reset/",views.verify_otp_reset, name='verify_otp_reset'),
    path("change_password/",views.change_password, name='change_password'),
    # path("accounts/password_reset/done/",views.forgot_password, name="password_reset_done"),
    # path("accounts/reset/<uidb64>/<token>/",views.forgot_password, name="password_reset_confirm"),
    # path("accounts/reset/done/",views.forgot_password, name="password_reset_complete"),
    

    path("logout/",views.user_logout, name='logout'),
]

userauths/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
# from phonenumber_field.phonenumber import PhoneNumber


class User(AbstractUser):
    username = models.EmailField(unique=True,null=True)
    # username = None
    # email = None
    # username = models.CharField(max_length=100, null=True, blank=True)
    mobile = models.CharField(unique=True,max_length=50)
    is_verified = models.BooleanField(default=False)

    USERNAME_FIELD = "username"
    REQUIRED_FIELDS = []

    def __str__(self):
        return self.first_name

userauths/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm,SetPasswordForm,PasswordResetForm
from userauths.models import User
# from phone_field import PhoneField
# from phonenumber_field.modelfields import PhoneNumberField

class UserRegisterForm(UserCreationForm):
    first_name = forms.CharField(widget=forms.TextInput(attrs={'placeholder':"First Name"}))
    last_name = forms.CharField(widget=forms.TextInput(attrs={'placeholder':"Last Name"}))
    mobile = forms.CharField(widget=forms.TextInput(attrs={'placeholder':"Mobile Number"}))
    username = forms.EmailField(widget=forms.TextInput(attrs={'placeholder':"Email",'class':"email_validate"}))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder':"Password"}))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder':"Confirm Password"}))
    agrrement = forms.BooleanField(required=False)
   
    class Meta:
        model = User
        fields = ['mobile','username','first_name','last_name']


class UserPasswordSetForm(SetPasswordForm):
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder':"Password"}))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder':"Confirm Password"}))
    class Meta:
        model = User
        fields = ['password1','password2']


class PasswordResetForm(PasswordResetForm):
    def __init__(self, *args, **kwargs):
        super(PasswordResetForm, self).__init__(*args, **kwargs)

    # captcha = ReCaptchaField(widget=ReCaptchaV2Checkbox())

userauths/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse,HttpResponseRedirect
from core.models import Cart,CartItem
from userauths.forms import UserRegisterForm
from django.contrib.auth import login,authenticate,logout
from django.contrib import messages
from django.conf import settings
from django.contrib.auth import get_user_model
from django.core.mail import send_mail
from django.conf import settings
import random
from core.views import _session_id,merge_carts



User = settings.AUTH_USER_MODEL
User = get_user_model()

def user_login(request):
    
    if request.user.is_authenticated:
        return redirect('core:index')

    if request.method == "POST":
        email = request.POST.get('email')
        password = request.POST.get('password')   

        try:
            user = User.objects.get(username=email)
        except:
            messages.warning(request,f"User with {email} dose not exist.")

        user = authenticate(request, username=email, password=password)
        if user is not None:
            if user.is_verified is False:
                messages.error(request,"Your are not verified")
                return redirect('userauths:login')    
            login(request,user)
            # Session cart checking
            merge_carts(request)        
            messages.success(request,"You are loggedIn")
            return redirect('core:index')
        else:
            messages.warning(request,"Invalid email or password")

    
    return render(request,'userauths/login.html')



def register_view(request):
    form = UserRegisterForm()
    if request.method == "POST":
        form = UserRegisterForm(request.POST or None)
        if form.is_valid():
            new_user = form.save()
            
            otp = int(random.randint(1000,9999))

            # Send the OTP to the user via email
            msg = f'OTP Verification, Your OTP is: {otp}' 
            send_mail(
                'Veify Email',
                msg,
                settings.EMAIL_HOST_USER,
                [new_user.username],
                fail_silently=False,
            )

            # Store the OTP in the session for verification
            request.session['otp'] = otp
            request.session['email'] = new_user.username

            # Redirect the user to the OTP verification page
            return redirect('userauths:verify_otp')
        
            # username = form.cleaned_data.get("username")
            # messages.success(request,f"Hey {username} your account was created successfully.")
            # new_user = authenticate(email = form.cleaned_data['email'],
            #                         passwod=form.cleaned_data['password1'])
            # login(request,new_user)
            # return redirect("core:index")

    context = {
        'form':form,
    }
    return render(request,'userauths/sign-up.html',context)


def send_otp(request,email):
    user = User.objects.get(username = email)
    otp = int(random.randint(1000,9999))
    print("Otp")
    print(otp)
    # Send the OTP to the user via email
    msg = f'OTP Verification, Your OTP is: {otp}' 
    send_mail(
        'Veify Email',
        msg,
        settings.EMAIL_HOST_USER,
        [email],
        fail_silently=False,
    )

    # Store the OTP in the session for verification
    request.session['otp'] = otp
    request.session['email'] = user.username

    # Redirect the user to the OTP verification page
    messages.success(request, "OTP sent!")
    return redirect('userauths:verify_otp')




def verify_otp(request):
    if request.method == 'POST':
        user_otp = int(request.POST['otp'])
        saved_otp = request.session.get('otp')
        if user_otp == saved_otp:
            # Verification successful
            email = request.session.get('email')
            # Create the user account or perform any other necessary actions
            # ...

            # Clear the session data
            del request.session['otp']
            del request.session['email']

            user = User.objects.get(username = email)
            messages.success(request,f"Hey {user.first_name} your account was created successfully.")
            login(request,user)
            user.is_verified = True
            user.save()

            return redirect("core:index")

        else:
            # Verification failed
            messages.error(request,"Invalid OTP")
            # return redirect('userauths:verify_otp')
    return render(request,'userauths/verify_otp.html')


def password_reset(request):
    if request.method == 'POST':
        email = request.POST.get('email')
        try:
            user = User.objects.get(username=email)
            request.session['reset_email'] = email
            return redirect("userauths:send_otp_for_reset",email)
        except:
            messages.warning(request,f"User with {email} dose not exist.")
            return redirect("userauths:forgot_password")
            
    return render(request,'userauths/forgot_password.html')


def send_otp_for_reset(request,email):
    user = User.objects.get(username = email)
    otp = int(random.randint(1000,9999))
    print("Otp")
    print(otp)
    # Send the OTP to the user via email
    msg = f'OTP Verification, Your OTP is: {otp}' 
    send_mail(
        'Veify Email',
        msg,
        settings.EMAIL_HOST_USER,
        [email],
        fail_silently=False,
    )

    # Store the OTP in the session for verification
    request.session['otp'] = otp
    request.session['email'] = user.username

    # Redirect the user to the OTP verification page
    messages.success(request, "OTP sent!")
    return redirect('userauths:verify_otp_reset')

def verify_otp_reset(request):
    if request.method == 'POST':
        user_otp = int(request.POST['otp'])
        saved_otp = request.session.get('otp')
        if user_otp == saved_otp:
            # Verification successful
            email = request.session.get('reset_email')
            # Create the user account or perform any other necessary actions
            # ...

            # Clear the session data
            

            
            messages.success(request, "Your email verified!.")
            return redirect("userauths:change_password")

        else:
            # Verification failed
            messages.error(request,"Invalid OTP")
            # return redirect('userauths:verify_otp')
    return render(request,'userauths/verify_otp_reset.html')

def change_password(request):
    if request.method == 'POST':
        password1 = request.POST['password1']
        password2 = request.POST['password2']
        email = request.session.get('reset_email')
        if password1 == password2:
            user = User.objects.get(username = email)
            user.set_password(password1)
            user.save()
            del request.session['otp']
            del request.session['reset_email']
            messages.success(request, 'Password succesfully changed')
            return redirect('userauths:login')
        else:
            messages.error(request, 'Passwords not matching')


    return render(request,'userauths/change_password.html')


def user_logout(request):
    logout(request)
    messages.success(request, "You are logout success", extra_tags="success")
    return redirect('userauths:login')

templates/userauths/change_password.html
{% extends 'partials/base.html' %}
{% load static %}
{% block content %}
    <main class="main pages">
        <div class="page-header breadcrumb-wrap">
            <div class="container">
                <div class="breadcrumb">
                    <a href="" rel="nofollow"><i class="fi-rs-home mr-5"></i>Home</a>
                    <span></span> Login
                </div>
            </div>
        </div>
        <div class="page-content pt-150 pb-150">
            <div class="container">
                <div class="row">
                    <div class="col-xl-8 col-lg-10 col-md-12 m-auto">
                        <div class="row">
                            
                            <div class="col-lg-6 col-md-8">
                                <div class="login_wrap widget-taber-content background-white">
                                    <div class="padding_eight_all bg-white">
                                        <div class="heading_s1">
                                            <h1 class="mb-5">Reset your password</h1>
                                        </div>
                                        
                                        <form method="post" action=" ">
                                            {% csrf_token %}
                                            <div class="form-group">
                                                <input type="password" required="" name="password1" placeholder="Enter password" />
                                            </div>
                                            <div class="form-group">
                                                <input type="password" required="" name="password2" placeholder="Confirm password" />
                                            </div>
                                            <div class="form-group">
                                                <button type="submit" class="btn btn-heading btn-block hover-up" name="login">Reset</button>
                                                
                                            </div>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </main>
{% endblock content %}
        

templates/userauths/forgot_password.html
{% extends 'partials/base.html' %}
{% load static %}
{% block content %}
    <main class="main pages">
        <div class="page-header breadcrumb-wrap">
            <div class="container">
                <div class="breadcrumb">
                    <a href="index.html" rel="nofollow"><i class="fi-rs-home mr-5"></i>Home</a>
                    <span></span> Login
                </div>
            </div>
        </div>
        <div class="page-content pt-150 pb-150">
            <div class="container">
                <div class="row">
                    <div class="col-xl-8 col-lg-10 col-md-12 m-auto">
                        <div class="row">
                            
                            <div class="col-lg-6 col-md-8 col-md-offset-6">
                                <div class="login_wrap widget-taber-content background-white">
                                    <div class="padding_eight_all bg-white">
                                        <div class="heading_s1">
                                            <h1 class="mb-5">Forgot Password</h1>
                                            
                                        </div>
                                        
                                        <form method="post" action=" ">
                                            {% csrf_token %}
                                            <div class="form-group">
                                                <input type="text" required="" name="email" placeholder="Enter your Email *" />
                                            </div>
                                            
                                            
                                            
                                            <div class="form-group">
                                                <button type="submit" class="btn btn-heading btn-block hover-up" name="login">Next</button>
                                            </div>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </main>
{% endblock content %}
        

templates/userauths/login.html
{% extends 'partials/base.html' %}
{% load static %}
{% block content %}
    <main class="main pages">
        <div class="page-header breadcrumb-wrap">
            <div class="container">
                <div class="breadcrumb">
                    <a href="index.html" rel="nofollow"><i class="fi-rs-home mr-5"></i>Home</a>
                    <span></span> Login
                </div>
            </div>
        </div>
        <div class="page-content pt-150 pb-150">
            <div class="container">
                <div class="row">
                    <div class="col-xl-8 col-lg-10 col-md-12 m-auto">
                        <div class="row">
                            <div class="col-lg-6 pr-30 d-none d-lg-block">
                                <img class="border-radius-15" src="{% static 'assets/imgs/page/login-1.png' %}" alt="" />
                            </div>
                            <div class="col-lg-6 col-md-8">
                                <div class="login_wrap widget-taber-content background-white">
                                    <div class="padding_eight_all bg-white">
                                        <div class="heading_s1">
                                            <h1 class="mb-5">Login</h1>
                                            <p class="mb-30">Don't have an account? <a href="{% url 'userauths:sign-up' %}">Create here</a></p>
                                        </div>
                                        
                                        <form method="post" action=" ">
                                            {% csrf_token %}
                                            <div class="form-group">
                                                <input type="text" required="" name="email" placeholder="Email *" />
                                            </div>
                                            <div class="form-group">
                                                <input required="" type="password" name="password" placeholder="Your password *" />
                                            </div>
                                            
                                            <div class="login_footer form-group mb-50">
                                                <div class="chek-form">
                                                    <div class="custome-checkbox">
                                                        <input class="form-check-input" type="checkbox" name="checkbox" id="exampleCheckbox1" value="" />
                                                        <label class="form-check-label" for="exampleCheckbox1"><span>Remember me</span></label>
                                                    </div>
                                                </div>
                                                <a class="text-muted" href="{% url 'userauths:password_reset' %}">Forgot password?</a>
                                            </div>
                                            <div class="form-group">
                                                <button type="submit" class="btn btn-heading btn-block hover-up" name="login">Log in</button>
                                            </div>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </main>
{% endblock content %}
        

templates/userauths/sign-up.html
{% extends 'partials/base.html' %}
{% load static %}
{% block content %}
    <main class="main pages">
        <div class="page-header breadcrumb-wrap">
            <div class="container">
                <div class="breadcrumb">
                    <a href="index.html" rel="nofollow"><i class="fi-rs-home mr-5"></i>Home</a>
                    <span></span> Pages <span></span> My Account
                </div>
            </div>
        </div>
        <div class="page-content pt-150 pb-150">
            <div class="container">
                <div class="row">
                    <div class="col-xl-8 col-lg-10 col-md-12 m-auto">
                        <div class="row">
                            <div class="col-lg-6 col-md-8">
                                <div class="login_wrap widget-taber-content background-white">
                                    <div class="padding_eight_all bg-white">
                                        <div class="heading_s1">
                                            <h1 class="mb-5">Create an Account</h1>
                                            <p class="mb-30">Already have an account? <a href="{% url 'userauths:login' %}">Login</a></p>
                                        </div>
                                        {% if form.errors %}
                                        <div class="alert alert-danger">
                                            <strong>
                                              {{form.errors}}
                                            </strong>
                                        </div>
                                        {% endif %}
                                        
                                        <form method="POST" action="">
                                            {% csrf_token %}

                                            <div class="form-group">
                                                {{ form.first_name }}
                                            </div>
                                            <div class="form-group">
                                                {{ form.last_name }}
                                            </div>
                                            <div class="form-group">
                                                {{ form.mobile }}
                                            </div>
                                            <div class="form-group">
                                                {{ form.username }}
                                            </div>
                                            <div class="form-group">
                                                {{ form.password1 }}
                                            </div>
                                            <div class="form-group">
                                                {{ form.password2 }}
                                            </div>
                                            
                                            <!-- <div class="login_footer form-group mb-50">
                                                <div class="chek-form">
                                                    <div class="custome-checkbox">
                                                        <input class="form-check-input" type="checkbox" name="checkbox" id="exampleCheckbox12" value="" />
                                                        <label class="form-check-label" for="exampleCheckbox12"><span>I agree to terms &amp; Policy.</span></label>
                                                    </div>
                                                </div>
                                                <a href="page-privacy-policy.html"><i class="fi-rs-book-alt mr-5 text-muted"></i>Lean more</a>
                                            </div> -->
                                            <div class="form-group mb-30">
                                                <button type="submit" class="btn btn-fill-out btn-block hover-up font-weight-bold" name="login">Submit &amp; Register</button>
                                            </div>
                                            <p class="font-xs text-muted"><strong>Note:</strong>Your personal data will be used to support your experience throughout this website, to manage access to your account, and for other purposes described in our privacy policy</p>
                                        </form>
                                    </div>
                                </div>
                            </div>
                            <!-- <div class="col-lg-6 pr-30 d-none d-lg-block">
                                <div class="card-login mt-115">
                                    <a href="#" class="social-login facebook-login">
                                        <img src="assets/imgs/theme/icons/logo-facebook.svg" alt="" />
                                        <span>Continue with Facebook</span>
                                    </a>
                                    <a href="#" class="social-login google-login">
                                        <img src="assets/imgs/theme/icons/logo-google.svg" alt="" />
                                        <span>Continue with Google</span>
                                    </a>
                                    <a href="#" class="social-login apple-login">
                                        <img src="assets/imgs/theme/icons/logo-apple.svg" alt="" />
                                        <span>Continue with Apple</span>
                                    </a>
                                </div>
                            </div> -->
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </main>
{% endblock content %}
        

templates/userauths/verify_otp.html
{% extends 'partials/base.html' %}
{% load static %}
{% block content %}
    <main class="main pages">
        <div class="page-header breadcrumb-wrap">
            <div class="container">
                <div class="breadcrumb">
                    <a href="" rel="nofollow"><i class="fi-rs-home mr-5"></i>Home</a>
                    <span></span> Login
                </div>
            </div>
        </div>
        <div class="page-content pt-150 pb-150">
            <div class="container">
                <div class="row">
                    <div class="col-xl-8 col-lg-10 col-md-12 m-auto">
                        <div class="row">
                            
                            <div class="col-lg-6 col-md-8">
                                <div class="login_wrap widget-taber-content background-white">
                                    <div class="padding_eight_all bg-white">
                                        <div class="heading_s1">
                                            <h1 class="mb-5">Verify Your Email</h1>
                                        </div>
                                        
                                        <form method="post" action=" ">
                                            {% csrf_token %}
                                            <div class="form-group">
                                                <input type="text" required="" name="otp" placeholder="Enter Your OTP" />
                                            </div>
                                            <div class="form-group">
                                                <button type="submit" class="btn btn-heading btn-block hover-up" name="login">Verify</button>
                                            </div>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </main>
{% endblock content %}
        