core/urls.py
from django.urls import path
from core import views

app_name = "core"

urlpatterns = [
    path("",views.index,name="index"),
    path("products/",views.product_list,name="product_list"),
    path("pd/<pid>/<str:slug>/",views.product_detail,name="product_detail"),
     path("get_variation_price/",views.get_variation_price,name="get_variation_price"),
    path("categories/",views.category_list,name="category_list"),

    path("search/",views.search,name="search"),
    
    #Cart
    path("add-to-cart/",views.add_cart_,name="add-to-cart"),
    # path("add_to_cart/",views.add_to_cart,name="add-to-cart"),
    path("remove_cart/",views.remove_cart,name="remove_cart"),
    path("delete_cart/<int:product_id>/<int:cart_item_id>/",views.delete_cart,name="delete_cart"),
    path("cart/",views.cart,name="cart"),
    path("increment_cart_item/",views.increment_cart_item,name="increment_cart_item"),
    path("remove_coupon/<int:coupon_id>",views.remove_coupon,name="remove_coupon"),

    # Whishlist
    path("add_to_wishlist/",views.add_to_wishlist,name="add-to-whishlist"),
    path("wishlist/",views.view_wishlist,name="wishlist"),
    path("wishlist/remove/<int:id>/",views.delete_wishlist_item,name="delete_wishlist_item"),

    
    
    # Apply coupon
    path("cart/apply_coupon/",views.apply_coupon,name="apply_coupon"),
    path("checkout/",views.checkout,name="checkout"),
    path("placeorder/",views.placeorder,name="placeorder"),
    path("order/payment/<str:orderno>/",views.payment,name="payment"),
    path("paymenthandler/",views.paymenthandler,name="paymenthandler"),
    # path("payment_success/",views.payment_success,name="payment_success"),
    path("checkout/success/<str:orderno>/",views.checkout_success,name="checkout_success"),


]

grocery_ecom/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("core.urls")),
    path("user/", include("userauths.urls")),
    path("user/", include("user.urls")),
    path("ckeditor/", include("ckeditor_uploader.urls")),
    path("superadmin/", include("superadmin.urls")),

    

]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import path
from user import views

app_name = "user"

urlpatterns = [
    path("account/",views.account, name="account"),
    
    path("address/",views.address, name="address"),
    path("address/add/",views.add_address, name="add_address"),
    path("address/edit/<int:id>/",views.edit_address, name="edit_address"),
    path("address/delete/<int:id>/",views.delete_address, name="delete_address"),

    path("orders/",views.orders, name="orders"),
    path("order/view/<int:id>/",views.order_details, name="order_details"),
    path("order/cancel_order/<int:id>/",views.cancel_order, name="cancel_order"),
    path("order/cancel_order_item/<int:id>/",views.cancel_order_item, name="cancel_order_item"),
    path("order/cancel_order_status/<int:id>/",views.cancel_order_status, name="cancel_order_status"),
    
    path("profile/",views.profile, name="profile"),

    path("accounts/password_change/",views.password_change, name="password_change"),

    path("wallet/",views.wallet, name="wallet"),
    path('invoice/<int:order_id>/', views.generate_invoice_pdf, name='generate_invoice_pdf'),
    
    
]

userauths/urls.py
from django.urls import path
from userauths import views

app_name = "userauths"

urlpatterns = [
    path("login/",views.user_login, name="login"),
    path("sign-up/",views.register_view, name="sign-up"),
    path("verify_otp/",views.verify_otp, name='verify_otp'),
    path("send_otp/<str:email>/",views.send_otp, name='send_otp'),


    path("send_otp_for_reset/<str:email>/",views.send_otp_for_reset, name='send_otp_for_reset'),
    # path("accounts/password_change/",views.password_change, name="password_change"),
    # path("accounts/password_change/done/",views.forgot_password, name="password_change_done"),
    path("accounts/password_reset/",views.password_reset, name="password_reset"),
    path("verify_otp_reset/",views.verify_otp_reset, name='verify_otp_reset'),
    path("change_password/",views.change_password, name='change_password'),
    # path("accounts/password_reset/done/",views.forgot_password, name="password_reset_done"),
    # path("accounts/reset/<uidb64>/<token>/",views.forgot_password, name="password_reset_confirm"),
    # path("accounts/reset/done/",views.forgot_password, name="password_reset_complete"),
    

    path("logout/",views.user_logout, name='logout'),
]

core/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse, JsonResponse, HttpResponseBadRequest
from core.models import Category, Vendor, Brand, Product, ProductItem, ProductImages, CartOrder, CartOrderItems, ProductReview, WhishList, Countrty, State, City, Address, Cart, CartItem, OrderAddress, Variation, Coupon, Wallet, WalletTransaction
from django.template.defaultfilters import slugify
from django.contrib.auth.decorators import login_required
from django.contrib import messages
# from cart.cart import Cart
from django.db.models import Q
import razorpay
import json
from django.views.decorators.csrf import csrf_exempt
from django.conf import settings
from django.utils import timezone
from django.core import serializers


def index(request):
    products = Product.objects.filter(
        featured=True, product_status="published",status = True,is_deleted = False)

    context = {
        'products': products
    }
    return render(request, 'core/index.html', context)


def product_list(request):
    products = Product.objects.filter(product_status="published",status = True,is_deleted = False)

    context = {
        'products': products
    }
    return render(request, 'core/products.html', context)


def search(request):
    products = Product.objects.filter(product_status="published")
    query = request.GET['query']
    c = request.GET['c']
    min_price = request.GET['min_price']
    max_price = request.GET['max_price']
    if query:
        products = Product.objects.filter(
            Q(description__icontains=query) | Q(title__icontains=query))
    if request.GET['c']:
        products = Product.objects.filter(category=request.GET['c'])

    if request.GET['min_price'] and request.GET['max_price']:
        products = Product.objects.filter(
            discount_price__range=(min_price, max_price))
    context = {
        'products': products,
        'query': query,
        'max_price': max_price,
        'min_price': min_price,
        'c': c

    }
    return render(request, 'core/products.html', context)


def category_list(request):
    categories = Category.objects.all()

    context = {
        'categories': categories
    }
    return render(request, 'core/categories.html', context)

# Prodcut Detail


def product_detail(request, pid, slug):
    product = Product.objects.get(pid=pid)
    p_images = product.p_images.all()

    context = {
        'product': product,
        'p_images': p_images,
    }
    return render(request, 'core/product-details.html', context)


def get_variation_price(request):
    if request.GET['id']:

        # try:
        if request.GET['id']:
            variation = Variation.objects.get(id=int(request.GET['id']))

            data = {
                'price': round(variation.get_variation_product_price(), 2),
                'mrp_price': variation.mrp_price if variation.mrp_price != 0.00 else variation.product.price,
            }

            new_off = ((float(data["price"]) /
                       float(data["mrp_price"])) * 100)-100
            data.update({'off': round(new_off, 2)})
            response = {
                'status': True,
                'data': data
            }
        # except:
        #     response = {
        #         'status':False,
        #         'data':None
        #     }
    return JsonResponse(response)


def cart(request):
    try:
        cart = Cart.objects.get(cart_id = _session_id(request))
    except:
        cart_items = None

    # if not cart.coupon:
    #     request.session['discount_amount'] = 0
    # print(request.session['discount_amount'])
    context = {
        'cart': cart,
    }
    return render(request, 'core/cart.html', context)


def _session_id(request):
    cart = request.session.session_key
    if not cart:
        cart = request.session.create()
    return cart

# Add to wishlist


@login_required(login_url="userauths:login")
def add_to_wishlist(request):
    product_id = request.GET['id']

    if request.user.is_authenticated:
        product = Product.objects.get(pk=product_id)
        wishlist, created = WhishList.objects.get_or_create(
            user=request.user, product=product)
        response = {
            'status': True,
            'message': 'Product added to wishlist',
            'whish_list_count': 1
        }
        return JsonResponse(response)
    else:
        # Redirect to login page or display an error message.
        return redirect('userauths:login')


@login_required(login_url="userauths:login")
def view_wishlist(request):

    products = WhishList.objects.filter(user=request.user)

    context = {'products': products}
    return render(request, 'core/user_account/wishlist.html', context)


@login_required(login_url="userauths:login")
def delete_wishlist_item(request, id):

    wishlist_item = WhishList.objects.get(id=id)

    wishlist_item.delete()
    messages.success(request, "Product removed from wishlist!")
    return redirect("core:wishlist")


@login_required(login_url="userauths:login")
def add_cart_(request):

    if 'discount_amount' in request.session:
        del request.session['discount_amount']
    product_variation = []
    product_id = request.GET['id']
    qty = request.GET['quantity']
    if request.GET['package_size']:
        size = request.GET['package_size']
    else:
        size = None
    # color       = request.GET['color']

    product = Product.objects.get(id=product_id)
    if size is not None:
        print("product have variations...")
        try:
            variation = Variation.objects.get(
                product=product, variation_category__iexact='package_size', pk=size)
            product_variation.append(variation)
        except:
            pass

    try:
        cart = Cart.objects.get(cart_id=_session_id(request))

    except Cart.DoesNotExist:
        if request.user.is_authenticated:
            cart = Cart.objects.create(
                cart_id=_session_id(request),
                user=request.user,
            )
        else:
            cart = Cart.objects.create(
                cart_id=_session_id(request)
            )
    cart.coupon = None
    cart.save()

    is_cart_items_exist = CartItem.objects.filter(
        product=product, cart=cart).exists()
    if is_cart_items_exist:
        # cart_item = CartItem.objects.get(product=product, cart=cart)
        cart_item = CartItem.objects.filter(product=product, cart=cart)

        ex_var_list = []
        id = []
        for item in cart_item:
            existing_varaiation = item.variations.all()
            ex_var_list.append(list(existing_varaiation))
            id.append(item.id)

        if size is not None:
            if product_variation in ex_var_list:
                print("product have variations...")
                print(existing_varaiation)
                # increase the item quanity
                index = ex_var_list.index(product_variation)
                item_id = id[index]
                item = CartItem.objects.get(product=product, id=item_id)
                item.qty += int(qty)
                item.save()
                # request.session['order_total'] += item.qty * item.product.discount_price
            else:
                item = CartItem.objects.create(
                    product=product, cart=cart, qty=qty)
                if len(product_variation) > 0:
                    item.variations.clear()
                    item.variations.add(*product_variation)
                    item.save()
        else:
            cart_item.qty += int(qty)
            cart_item.save()

        # if ((product.stock_count)-(cart_item.qty + int(qty))) < 0:
        #     response = {
        #         'status':False,
        #         'message':'Out of Stock'
        #     }
        #     return JsonResponse(response)
        # cart_item.qty += int(qty)

    else:
        if ((product.stock_count) - int(qty)) < 0:
            response = {
                'status': False,
                'message': 'Out of Stock'
            }
            return JsonResponse(response)
        cart_item = CartItem.objects.create(
            cart=cart,
            product=product,
            qty=qty
        )
        if size is not None:
            if len(product_variation) > 0:
                cart_item.variations.clear()
                cart_item.variations.add(*product_variation)

        cart_item.save()

    response = {
        'status': True,
        'message': 'Product added to Cart',
        'totalcartitems': CartItem.objects.filter(cart=cart).count()
    }
    return JsonResponse(response)


@login_required(login_url="userauths:login")
def increment_cart_item(request):

    qty = 1

    try:
        cart_id = request.GET['cart_id']
        cart_item_id = request.GET['cart_item_id']
        cart = Cart.objects.get(pk=cart_id)
        if 'discount_amount' in request.session:
            del request.session['discount_amount']
            cart.coupon = None
            cart.save()
        cart_item = CartItem.objects.get(pk=cart_item_id)
        if ((cart_item.product.stock_count) - int(cart_item.qty+qty)) < 0:
            response = {
                'status': False,
                'message': 'Out of Stock'
            }
            return JsonResponse(response)
        cart_item.qty += int(qty)
        cart_item.save()
        messages.success(request, "Product quantity incremented")

        response = {
            'status': True,
            'message': 'Product added to Cart',
            'totalcartitems': 1
        }

    except:
        response = {
            'status': False,
            'message': 'Error occured'
        }
    return JsonResponse(response)


def add_cart(request, product_id, qty=1):
    product = Product.objects.get(id=product_id)

    if request.user.is_authenticated:
        cart_item, created = CartItem.objects.get_or_create(
            user=request.user, product=product)
    else:

templates/core/user_account/address.html
{% extends 'partials/base.html' %}
{% load mathfilters %}
{% load static %}
{% block content %}
<main class="main pages">
    <div class="page-header breadcrumb-wrap">
        <div class="container">
            <div class="breadcrumb">
                <a href="index.html" rel="nofollow"><i class="fi-rs-home mr-5"></i>Home</a>
                <span></span> Pages <span></span> My Account
            </div>
        </div>
    </div>
    <div class="page-content pt-150 pb-150">
        <div class="container">
            <div class="row">
                <div class="col-lg-10 m-auto">
                    <div class="row">
                        <div class="col-md-3">
                            {% include "core/user_account/left_menu.html" %}
                        </div>
                        <div class="col-md-9">
                            <div class="tab-content account dashboard-content pl-50">
                                
                                <div class="tab-pane fade active show" id="address" role="tabpanel" aria-labelledby="address-tab">
                                    <div class="row">
                                        <div class="card-header">
                                            <h3 class="mb-0">Address</h3>
                                            <a class="btn  mr-10 mb-sm-15" style="float: right;" href="{% url 'user:add_address' %}"><i class="fi-rs-add mr-10"></i>Add New Address</a>
                                        </div>
                                        {% for a in addresses %}
                                        <div class="col-lg-6">
                                            <div class="card mb-3 mb-lg-0">
                                                
                                                <div class="card-body">
                                                    <address>
                                                        {{a.first_name}} {{a.last_name }}<br />
                                                        {{a.mobile}}<br/>
                                                        {{a.email}}<br/>
                                                        Address: {{a.line1}}<br/>
                                                        {{a.pincode}}
                                                        
                                                    </address>
                                                    {% if a.is_default %}<p> Default</p>{% endif %}
                                                    <a href="{% url 'user:edit_address' a.id %}" class="btn-small">Edit</a> | 
                                                    <a onclick="return confirm('Are you sure?')" href="{% url 'user:delete_address' a.id %}" class="btn-small btn-danger">Delete</a>
                                                </div>
                                            </div>
                                        </div>
                                        {% endfor %}
                                    </div>
                                </div>
                                <div class="tab-pane fade" id="account-detail" role="tabpanel" aria-labelledby="account-detail-tab">
                                    <div class="card">
                                        <div class="card-header">
                                            <h5>Account Details</h5>
                                        </div>
                                        <div class="card-body">
                                            <p>Already have an account? <a href="page-login.html">Log in instead!</a></p>
                                            <form method="post" name="enq">
                                                <div class="row">
                                                    <div class="form-group col-md-6">
                                                        <label>First Name <span class="required">*</span></label>
                                                        <input required="" class="form-control" name="name" type="text" />
                                                    </div>
                                                    <div class="form-group col-md-6">
                                                        <label>Last Name <span class="required">*</span></label>
                                                        <input required="" class="form-control" name="phone" />
                                                    </div>
                                                    <div class="form-group col-md-12">
                                                        <label>Display Name <span class="required">*</span></label>
                                                        <input required="" class="form-control" name="dname" type="text" />
                                                    </div>
                                                    <div class="form-group col-md-12">
                                                        <label>Email Address <span class="required">*</span></label>
                                                        <input required="" class="form-control" name="email" type="email" />
                                                    </div>
                                                    <div class="form-group col-md-12">
                                                        <label>Current Password <span class="required">*</span></label>
                                                        <input required="" class="form-control" name="password" type="password" />
                                                    </div>
                                                    <div class="form-group col-md-12">
                                                        <label>New Password <span class="required">*</span></label>
                                                        <input required="" class="form-control" name="npassword" type="password" />
                                                    </div>
                                                    <div class="form-group col-md-12">
                                                        <label>Confirm Password <span class="required">*</span></label>
                                                        <input required="" class="form-control" name="cpassword" type="password" />
                                                    </div>
                                                    <div class="col-md-12">
                                                        <button type="submit" class="btn btn-fill-out submit font-weight-bold" name="submit" value="Submit">Save Change</button>
                                                    </div>
                                                </div>
                                            </form>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</main>
{% endblock content %}

templates/core/user_account/left_menu.html
{% load menu_tags %}
<div class="dashboard-menu">
    <ul class="nav flex-column" role="tablist">
        <li class="nav-item">
            <a class="nav-link {% is_active request 'user:account' %}" href="{% url 'user:account' %}" ><i class="fi-rs-settings-sliders mr-10"></i>Dashboard</a>
        </li>
        <li class="nav-item">
            <a class="nav-link {% is_active request 'user:orders' %}" href="{% url 'user:orders' %}" ><i class="fi-rs-shopping-bag mr-10"></i>Orders</a>
        </li>
        
        <li class="nav-item">
            <a class="nav-link {% is_active request 'user:address' %}"  href="{% url 'user:address' %}" ><i class="fi-rs-marker mr-10"></i>My Address</a>
        </li>
        <li class="nav-item">
            <a class="nav-link {% is_active request 'user:profile' %}" href="{% url 'user:profile' %}" ><i class="fi-rs-user mr-10"></i>Account details</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'userauths:logout' %}"><i class="fi-rs-sign-out mr-10"></i>Logout</a>
        </li>
    </ul>
</div>

templates/core/user_account/profile.html
{% extends 'partials/base.html' %}
{% load mathfilters %}
{% load static %}
{% block content %}
<main class="main pages">
    <div class="page-header breadcrumb-wrap">
        <div class="container">
            <div class="breadcrumb">
                <a href="{% url 'core:index'%}" rel="nofollow"><i class="fi-rs-home mr-5"></i>Home</a>
                <span></span> Pages <span></span> My Account
            </div>
        </div>
    </div>
    <div class="page-content pt-150 pb-150">
        <div class="container">
            <div class="row">
                <div class="col-lg-10 m-auto">
                    <div class="row">
                        <div class="col-md-3">
                            {% include "core/user_account/left_menu.html" %}
                        </div>
                        <div class="col-md-9">
                            <div class="tab-pane fade active show" id="account-detail" role="tabpanel" aria-labelledby="account-detail-tab">
                                <div class="card">
                                    <div class="card-header">
                                        <h5>Account Details</h5>
                                    </div>
                                    <div class="card-body">
                                        <form method="post" name="enq" action="">
                                            {% csrf_token %}
                                            <div class="row">
                                                <div class="form-group col-md-6">
                                                    <label>First Name <span class="required">*</span></label>
                                                    <input required="" class="form-control" value="{{ user.first_name }}" name="first_name" type="text" />
                                                </div>
                                                <div class="form-group col-md-6">
                                                    <label>Last Name <span class="required">*</span></label>
                                                    <input required="" class="form-control" value="{{ user.last_name }}" name="last_name" />
                                                </div>
                                                
                                                <div class="form-group col-md-12">
                                                    <label>Email Address <span class="required">*</span></label>
                                                    <input required="" class="form-control" value="{{ user.username }}" disabled name="email" type="email" />
                                                </div>
                                                <div class="form-group col-md-12">
                                                    <label>Mobile <span class="required">*</span></label>
                                                    <input required="" class="form-control" value="{{ user.mobile }}" disabled name="mobile" type="text" />
                                                </div>
                                                <p><a href="{% url 'user:password_change'%}">Change Password</a></p>
                                                <div class="col-md-12">
                                                    <button type="submit" class="btn btn-fill-out submit font-weight-bold" name="submit" value="Submit">Save Change</button>
                                                </div>
                                            </div>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</main>
{% endblock content %}

templates/core/user_account/wishlist.html
{% extends 'partials/base.html' %}
{% load mathfilters %}
{% load static %}
{% block content %}
<main class="main">
    <div class="page-header breadcrumb-wrap">
        <div class="container">
            <div class="breadcrumb">
                <a href="{% url 'core:index'%}" rel="nofollow"><i class="fi-rs-home mr-5"></i>Home</a>
                <span></span> Wishlist
            </div>
        </div>
    </div>
    <div class="container mb-80 mt-50">
        {% if products is not none and products|length != 0%}
        <div class="row">
            <div class="col-lg-8 mb-40">
                <h1 class="heading-2 mb-10">Your Wishlist</h1>
                <div class="d-flex justify-content-between">
                    <h6 class="text-body">There are <span class="text-brand">{{ products|length }}</span> products in your wishlist</h6>
                    <!-- <h6 class="text-body"><a href="#" class="text-muted"><i class="fi-rs-trash mr-5"></i>Clear Wishlist</a></h6> -->
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-8">
                <div class="table-responsive shopping-summery">
                    <table class="table table-wishlist">
                        <thead>
                            <tr class="main-heading">
                                
                                <th scope="col" >Product</th>
                                <th scope="col"> Price</th>
                                <th scope="col" class="end">Remove</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for item in products %}
                            <tr class="pt-30">
                                
                                <td class="image product-thumbnail pt-40">
                                    <a class="" href="{% url 'core:product_detail' item.product.pid item.product.title|slugify %}"><img src="{{ item.product.image.url }}" alt="#"></a>
                                    <h6 class="mb-5"><a class="product-name mb-10 text-heading" href="{% url 'core:product_detail' item.product.pid item.product.title|slugify %}">{{item.product.title|truncatechars:20 }}</a></h6>
                                </td>
                                
                                <td class="price" data-title="Price">
                                    <h4 class="text-body">₹{{item.product.discount_price}} </h4>
                                </td>
                                
                                
                                <td class="action text-center" data-title="Remove"><a href="{% url 'core:delete_wishlist_item' item.id %}" class="text-body" ><i class="fi-rs-trash"></i></a></td>
                            </tr>
                            {% endfor %}
                            
                        </tbody>
                    </table>
                </div>
                <div class="divider-2 mb-30"></div>
                <!-- <div class="cart-action d-flex justify-content-between">
                    <a class="btn "><i class="fi-rs-arrow-left mr-10"></i>Continue Shopping</a>
                    <a class="btn  mr-10 mb-sm-15"><i class="fi-rs-refresh mr-10"></i>Update Cart</a>
                </div> -->
                
            </div>
            
        </div>
        {% else %}
        <section class="newsletter mb-15 wow animate__animated animate__fadeIn">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="position-relative newsletter-inner">
                            <div class="newsletter-content">
                                <h2 class="mb-20">
                                    Let's fill the empty Wishlist
                                </h2>
                                <a class="btn" href="{% url 'core:index' %}">Continue Shopping</a>
                                
                            </div>
                            <img src="{% static 'assets/imgs/banner/banner-9.png' %}" alt="newsletter" />
                        </div>
                    </div>
                </div>
            </div>
        </section>
        {% endif %}
    </div>
</main>
{% endblock content%}